### PR TITLE
Adding welcome messages from sbm

### PR DESCRIPTION
**Pull request by bruskiza**

### CODE REVIEW

**Comment by bruskiza** [comment]
@rudigiesler @smn here are the welcome messages that are prepended to the app.
Review please.

**Comment by smn** [comment]
Are we sure about the filename? The snippet @rudigiesler shared in Slack mentioned `static/audio/registation/eng_NG/welcome_mother.mp3` not `welcome_message.mp3`

**Comment by rudigiesler** [comment]
I think that the filename is `welcome_mother.mp3` instead of `welcome_message.mp3` https://github.com/praekelt/hellomama-registration/blob/2549c8314a1a05acea513b5dda18fea9a8223723/registrations/tasks.py#L221

**Comment by bruskiza** [comment]
@rudigiesler @smn re-review?

**Comment by smn** [comment]
:+1:

**Comment by rudigiesler** [comment]
:+1:

**Pull request merged**
