### PR TITLE
MOMNG-79 - Aligning filenames based on js_box requirements

### PR DESCRIPTION
**Pull request by bruskiza**

### CODE REVIEW

**Comment by smn** [comment]
@imsickofmaps & @gsvr does this look right to you?

**Comment by imsickofmaps** [comment]
@smn so far they seem logical renames

**Comment by smn** [comment]
@bruskiza how are you mapping the old to the new file names? Where did the old ones come from?

**Comment by bruskiza** [comment]
@smn took them out of the ticket MOMNG-79
and then asked Chichi and Janie to match what they had vs. what was being looked for.

That sheet is here: https://docs.google.com/spreadsheets/d/1VM1wJFbc4HiHaFjmpeUd-i9zRheeLWbMl7UIZkfto6k/edit#gid=1750738148

**Comment by bruskiza** [comment]
@imsickofmaps done with the renames that I can see.
There are still leftover `_c*_` files.
Any suggestions how I can figure out what they need to be renamed to?

**Comment by bruskiza** [comment]
@gsvr @imsickofmaps poink^^^

**Comment by imsickofmaps** [comment]
@bruskiza listen to the `_c` files? That might help you determine where they go in the flow or if they're dropped states from the flow.

**Comment by bruskiza** [comment]
science! will do that. thanks @imsickofmaps

**Comment by bruskiza** [comment]
Hi @imsickofmaps, am releasing this for now... will pick up the rest as a separate PR.

**Pull request merged**
