### PR TITLE
Use json.dumps(), boolean was not working

### PR DESCRIPTION
**Pull request by erikh360**

### CODE REVIEW

**Review by rudigiesler — APPROVED** [review]
Since we're using python `requests`, we can just have `json=data` in the `session.patch`, ie `session.patch(url, json=data, headers=headers)`. Either way, looks good to me.

**Comment by rudigiesler** [comment]
One last thing, how come no tests picked this up? Do we maybe need a test for this?

**Comment by erikh360** [comment]
The patch requests are there, it's just not validating the json payload:

`
# mock patch subscription request
        responses.add(
            responses.PATCH,
            'http://localhost:8005/api/v1/subscriptions/%s/' % subscription_id,
            json={"active": False},
            status=200, content_type='application/json',
        )
`

**Comment by rudigiesler** [comment]
Ah okay. I see. Is the payload maybe something we would want to validate? If not, then :+1: on this PR.

**Comment by erikh360** [comment]
I think we should actually be changing this to use the `seed-services-client`, for now I'm merging this.

**Pull request merged**
