### PR TITLE
Add sms send on successful unique id generation for hcws

### PR DESCRIPTION
**Pull request by rudigiesler**

### CODE REVIEW

**Comment by rudigiesler** [comment]
Not yet done, this is how far I've gotten.

**Comment by KaitCrawford** [comment]
@rudigiesler @miltontony ready for review.
I've decided to add the button to resend the sms / regenerate codes in a new PR because it's getting complicated and I don't want it to hold up this work.

**Comment by rudigiesler** [comment]
Looks good to me, :+1:, but I think it will be good to have someone who hasn't written code in this PR to review it?

**Comment by smn** [comment]
:+1: thanks @KaitCrawford! 🍰

**Pull request merged**
